import type { Metadata } from "next";
import '@/public/assets/css/style.css'; 
import StoreProvider from "@/components/store-provider";
export const metadata: Metadata = {
  title: "CRM Dashboard",
  description: "Generated by Saleh Alabidi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
